# Field Parameters 
dim: 128
num_output_chans: 2
output_chan_width: 0.20 # in mm 
LG_modes: [[3,0], [5,0]]
w0: 0.10 # in mm
gauss_filter_sigma: 500
channel_sep: 1.5
circle_radius: 1.5

# Experimental Parameters of the Setup
num_phase_maps_near: 1
num_phase_maps_far: 0

rot_angle: '0' # Rotates the incident field by rot_angle 
fixedRotation: True 
randomRotation: False

# Simulates the lens
simulateLens: False
fourier_length: 10 # in cm 

# Simulates the experiment with multiple phase screens 
multiPhaseLens: False
multiPhase: False
z_o: 30 # in cm

# Genetic Parameters
num_of_gens: 1.5e5
gen_start: 1.e4
parents_mating: 4
sol_per_pop: 20
crossover_prob: None
mutation_type: 'adaptive'
mutation_percent: 15
mutation_prob: (0.01,0.0005) # high and low mutation probabilities for adaptive mutation
random_mutation_min_val: -0.1 # units of np.pi
random_mutation_max_val: 0.1  # units of np.pi
gen_saturate: 20000
parent_c: 1.0
parent_k: 0.5
ga_instance: "cinque_hopf_one_bread"
keep_elitism: 2 # number of best solutions to keep per generation
fitness_func: "bread"

# Do we generate knots instead? 
isKnot: True
knotType: ['Cinquefoil', 'Hopflink']
shapeParams: [[2.0,2.0,1.0],[0.6,0.6,1.0]]